name: Render Model Card PDF

on:
  push:
    branches: [ main ]

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Quarto CLI & TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '1.7.31'
          tinytex: true

      - name: Install Nimbus Sans font (Helvetica equivalent)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-fonts-recommended

      - name: Clone Quarto Extension (quarto_titlepages)
        run: |
          git clone --depth=1 https://github.com/nmfs-opensci/quarto_titlepages.git
          mkdir -p _extensions/titlepage
          cp -r quarto_titlepages/_extensions/titlepage/* _extensions/titlepage/

      - name: Render PDF
        run: |
          quarto render model_card_modern.qmd --to titlepage-pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
