name: Render Model Card PDF
on:
  push:
    branches: [ main ]
jobs:
  render-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Quarto CLI & TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '1.7.31'
          tinytex: true

      - name: Clone quarto_titlepages extension
        run: |
          mkdir -p _extensions/nmfs-opensci
          git clone --depth 1 --filter=blob:none --sparse https://github.com/nmfs-opensci/quarto_titlepages.git _extensions/nmfs-opensci/quarto_titlepages
          cd _extensions/nmfs-opensci/quarto_titlepages
          git sparse-checkout init --cone
          git sparse-checkout set _extension
          mv _extension/* .
          rm -rf _extension .git
          cd ../../../..

      - name: Copy extension files for Quarto
        run: |
          mkdir -p _extensions/titlepage
          cp -r temp_quarto_titlepages/_extensions/titlepage/* _extensions/titlepage

      - name: Render PDF
        run: |
          quarto render model_card_modern.qmd --to titlepage-pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
