# .github/workflows/render-pdf.yml
name: Render Model Card PDF

on:
  push:
    branches: [ main ]


jobs:
  render-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Quarto CLI & TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '1.7.31'
          tinytex: true

      - name: Install title-page extension
        run: |
          quarto install extension nmfs-opensci/quarto_titlepages

      - name: Render PDF
        run: |
          quarto render model_card_modern.qmd --to titlepage

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
