name: Render Model Card PDF

on:
  push:
    branches: [ main ]

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Quarto and TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '1.7.31'
          tinytex: true

      - name: Install Required LaTeX Packages
        run: |
          tlmgr install tcolorbox xcolor fancyhdr geometry fontspec

      - name: Render Model Card
        run: |
          quarto render model_card_modern.qmd --to pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
