name: Render Model Card PDF

on:
  push:
    branches: [ main ]

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Quarto CLI & TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '1.7.31'
          tinytex: true

      - name: Cache TinyTeX
        uses: actions/cache@v3
        with:
          path: ~/.TinyTeX
          key: ${{ runner.os }}-tinytex-${{ hashFiles('**/*.qmd') }}

      - name: Install TeX Gyre Fonts and Rebuild Font Map
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-fonts-extra
          sudo updmap-sys

      - name: Debug Available Fonts (Optional)
        run: |
          fc-list : family | sort
          kpsewhich --var-value=TEXMFMAIN
          kpsewhich texmf.cnf
          kpsewhich TeXGyreHeros-Regular.otf || echo "TeXGyreHeros-Regular.otf not found in LaTeX paths"

      - name: Clone Quarto Extension (titlepages)
        run: |
          git clone --depth=1 https://github.com/nmfs-opensci/quarto_titlepages.git
          mkdir -p _extensions/titlepage
          cp -r quarto_titlepages/_extensions/titlepage/* _extensions/titlepage/

      - name: Render PDF
        run: |
          quarto render model_card_modern.qmd --to titlepage-pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
