name: Render Model Card PDF

on:
  push:
    branches: [ main ]

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install TeX Live Full
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '1.7.31'
          tinytex: false  # Disable TinyTeX since we use TeX Live

      - name: Render Model Card
        run: |
          quarto render model_card_modern.qmd --to pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-card-pdf
          path: _output/*.pdf
